name: Code Analysis Workflow

on:
  push:
    branches: [development, ci/cd]
  pull_request:
    branches: [development]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run eslint

      - name: Run Prettier
        run: bun run prettier --check .
      
      - name: Generate Prisma Client
        run: bun run prisma generate
      
      - name: Run TypeScript Compiler
        run: bun run tsc